### ISSUE TITLE
Allow different duty tiers

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/CivDuties#1]
Not sure what exactly would be the way to approach this inbetween PermissionEx and this plugin, but basically it would be nice if we could have different duty tiers. Right now everyone with duty just gets put in spectator and can tp, but it would be nice if we could have another tier, which also gets access to /gamemode and namelayer.admin (which bypasses everything since perm rework).

**Comment by ProgrammerDan** [comment]
Hmm, if we're using PEX's api as a dependency, could probably just set it up using groups; temporarily join the player to the group that has the correct permission set when in duty mode, remove them when out.

**Comment by Maxopoly** [comment]
Yeah, I think it already supports adding the player temporarily to certain pex groups, but it doesn't allow different tiers yet.

**Comment by idoash4** [comment]
The best way to approach this will be adding the player to permission groups based on the permissions he has before entering duty. So if a player has the permission duty.mod he will be added to X groups while in duty but if he has the permission duty.admin he will be added to Y groups while in duty. We already have support for temp groups in the current version so adding this will be quite simple.

**Comment by rourke750** [comment]
Can you potentially add command functionality too.  like doing /duty will run certain commands based on your group.

**Comment by Maxopoly** [comment]
It already does that

**Comment by idoash4** [comment]
https://github.com/Civcraft/CivDuties/pull/5
